### ISSUE TITLE
[수정] 식당DB, 메뉴DB 구현

### ISSUE THREAD

**Issue by sejoonkim** [sungpyocho/vision-for-everyone#17]
mongoDB로 식당, 메뉴 구현

특징
- nested DB 구성
- 식당은 고려대, 서울대 학식, 스타벅스 추가함
- 메뉴는 스타벅스 메뉴만 추가함

**Comment by sungpyocho** [comment]
Visual Studio에서 3명 공동 작업 완료했으므로, close
