### ISSUE TITLE
[기능구현] 주문 영수증 띄우기

### ISSUE THREAD

**Issue by SnowLeopardMoonBear** [sungpyocho/vision-for-everyone#18]
주문 완료시 대기번호가 포함된 영수증 카드를 띄워주려 합니다.

개발 스텝
1. 영수증 템플릿 만들기
2. 주문 완료되었음을 프론트엔드에서 인식케 하기
3. 백엔드에서 프론트엔드로 주문정보 가져오기
4. 주문완료시 주문정보 담긴 영수증을 띄우기

**Comment by sejoonkim** [comment]
2 new commits pushed to master
6c96d7b8 - show prop data to receipt
a30c4deb - make Menu DB more simple

**Comment by sungpyocho** [comment]
영수증 주문 개수 추가 때문에 다시 오픈했습니다,
