### ISSUE TITLE
[기능구현] 튜토리얼 페이지 맵, 메뉴 연동

### ISSUE THREAD

**Issue by SnowLeopardMoonBear** [sungpyocho/vision-for-everyone#25]
프로그레스바 인텐트 매칭만 되면 튜토리얼 완성

**Comment by sungpyocho** [comment]
남은 문제: 마지막 대기표 나왔을 때 인텐트 매칭이 안되는 문제(80퍼에서 멈추는 현상)
-> 어떻게 바꿀 것인가?
-> Receipt 컴포넌트가 떴을 때 state를 바꿔주는 방법?

**Comment by sungpyocho** [comment]
완료된 문제이므로 CLOSE합니다.
