### ISSUE TITLE
[기능수정] 카카오페이 iframe 리디렉트 시 헤더 컴포넌트 렌더링 방지

### ISSUE THREAD

**Issue by sejoonkim** [sungpyocho/vision-for-everyone#38]
**기존 문제점**
클래스를 참조해서 display none을 하는 것 -> https://kiwe.team에서 header의 클래스명이 달라 iframe에서 리디렉트 시 화면 렌더링 오류 발생.

**해결 방안**
App.js에서 url을 분석했을때 kakaopay가 있다면 헤더 컴포넌트 렌더링 안 하도록 구현 완료.

**Comment by sungpyocho** [comment]
#39 로 해결 완료.
