### ISSUE TITLE
[버그] 모바일 환경 배터리 절약 모드시 랜딩페이지 모션 autoplay 불가

### ISSUE THREAD

**Issue by SnowLeopardMoonBear** [sungpyocho/vision-for-everyone#40]
**버그 설명**
모바일 환경(iOS)에서 저전력 모드시, 첫페이지 모션이 자동재생되지 않습니다. 또한, 이 상황에서 모션을 클릭하면, 첫 모션이 재생되지 않고 바로 다음 모션으로 넘어갑니다.

**버그 재현**
1. iOS 저전력 모드 활성화
2. 키위 랜딩페이지 들어감

**올바른 작동 방법**
저전력 모드에서 무리없이 첫 모션을 볼 수 있으면서, 일반적인 환경에서도 이질감 없이 의도대로 작동

**🎸**
기타 아이콘이 너무 귀여워서 남겨뒀습니다.

**Comment by sungpyocho** [comment]
이거 방금 풀리퀘로 해결된 버그인가요?

**Comment by SnowLeopardMoonBear** [comment]
> 이거 방금 풀리퀘로 해결된 버그인가요?

네 맞습니다
