### ISSUE TITLE
[핫픽스]랜딩페이지 사운드, 튜토리얼 최하단 키위가입하기 버튼

### ISSUE THREAD

**Issue by SnowLeopardMoonBear** [sungpyocho/vision-for-everyone#57]
1. 랜딩페이지에서 건너뛰기 클릭시에도 로고 사운드 재생하기
2. 튜토리얼 마지막에 키위 가입하기 버튼 추가

**Comment by sungpyocho** [comment]
remote를 review 브랜치로 바꿔주신 후, 다시 풀리퀘 부탁합니다.
(commit 내역이 1개만 있어야 정상. 만약 review로 머지했다는 제 커밋이 같이 반영되면 문제)

**Comment by sungpyocho** [comment]
테스트 상황으로 시간이 없으니, 우선 73c3cbb번으로 커밋했습니다.
